$id = $ARGV[0];
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/kernel_$id\_1.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/kernel_$id\_2.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/kernel_$id\_3.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/kernel_$id\_4.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/kernel_$id\_5.log");

