$id = $ARGV[0];
print $id;
print("\nadb -s $id logcat -c");
system("adb -s $id logcat -c");
print("\nadb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_1.log");
system("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_1.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
print("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_2.log");
system("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_2.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
print("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_3.log");
system("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_3.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
print("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_4.log");
system("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_4.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
print("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_5.log");
system("adb -s $id logcat -v threadtime | tee ./Logs/adb_$id\_5.log");
